"""Add passcode field to Group model

Revision ID: 555bae821a1a
Revises: 
Create Date: 2024-10-16 22:44:02.789764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555bae821a1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('passcode', sa.String(length=10), nullable=False, unique=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
